name: test
on:
  push
jobs:
  molecule:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - ubuntu2004
        scenario: 
          - default
    steps:
      - name: Check out codebase
        uses: actions/checkout@v2

      - name: mkdir
        run: mkdir -p /home/runner/.ansible/collections/m4eba/ 
        
      - name: link
        run: ln -s . /home/runner/.ansible/collections/m4eba/etcd

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install requirements
        run: pip3 install -r requirements.txt

      - name: Install test dependencies
        run: pip3 install ansible molecule[docker] docker

      - name: Run role tests
        run: >-
          molecule --version &&
          ansible --version &&
          docker --version &&
          molecule --debug -vvvv test -s ${{ matrix.scenario }}
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}